providers:
  logic:
    model: gpt-4-turbo
    api_key_env: OPENAI_KEY
  emotion:
    model: claude-3-opus
    api_key_env: ANTHROPIC_API_KEY
  fallback:
    model: gpt-3.5-turbo
    api_key_env: OPENAI_KEY

